CC = g++ // 원하는 컴파일러 지정
all:
	$ (CC) g++ main.cpp hello.cpp
test:
	g++ main.cpp shape.cpp circle.cpp line.cpp

make 하면 all 에있는거 실행
make test 하면 test에 있는 것 실행

make툴은 타자를 줄여주는게 아니라
변경되는 파일만 objec 파일만 둬서 컴파일 되는 시간을 줄인다.
-> 큰 프로젝트에 있는 다양한 파일을 효과적으로 컨트롤 함.
